trigger:
  branches:
    include: [ main ]
  paths:
    include: [ result/** ]

extends:
  template: pipelines/ci-template.yml

parameters:
  serviceName: 'result'
  servicePath: 'result'
