trigger:
  branches:
    include: [ main ]
  paths:
    include: [ worker/** ]

extends:
  template: pipelines/ci-template.yml

parameters:
  serviceName: 'worker'
  servicePath: 'worker'
