apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result

  template:
    metadata:
      labels:
        app: result

    spec:
      containers:
      - name: result
        image: cloudvotingacr.azurecr.io/result:38

        ports:
        - containerPort: 80

        env:
        - name: POSTGRES_HOST
          value: db
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: REDIS_HOST
          value: redis
